module.exports = {
	ownerIds: [""], //- Adicione aqui o seu ID.
	adminIds: [""], //- Adicione aqui os IDs dos administradores do seu bot.
	token: process.env.token || "", //- Adicione aqui o token do seu bot.
	default_prefix: "", //- Adicione aqui o prefixo padrão do seu bot.
	secretcookie: "kingfofo", //- Isso aqui é só para brincar mesmo ,-, 
}