/**
 * @AUTHOR
 * Name | @ricardo-as1
 * Instagram | https://www.instagram.com/kingzin.021/
 * GitHub | https://github.com/ricardo-as1
 * @INFORMAÇÕES_DO_BOT
 * Name | Hyouka
 * Description | Um bot de moderação e diversão para servidores do Discord.
 * @LINKS 
 * Repository | (https://github.com/ricardo-as1/Hyouka.git)
 * Support Server | (https://discord.gg/QxQUZbv7df)
 */

module.exports = {
	ownerIds: [""], //- Adicione aqui o seu ID.
	adminIds: [""], //- Adicione aqui os IDs dos administradores do seu bot.
	token: process.env.token || "", //- Adicione aqui o token do seu bot.
	default_prefix: "", //- Adicione aqui o prefixo padrão do seu bot.
	secretcookie: "kingfofo", //- Isso aqui é só para brincar mesmo ,-, 
}